<?php
/** @var \MagentoEse\LookBook\Block\LookBook $block */
?>
<?php $lookCollection = $block->getCurrentCategory()->getChildrenCategories() ?>
<div class="lookbook">
    <div class="prev"></div>
    <div class="next"></div>
    <div class="lookbook-carousel" data-mage-init='{
            "MagentoEse_LookBook::carousel": {
                "items": 1,
                "loop": true,
                "autoplay": false,
                "autoplayHoverPause": true,
                "responsive": true,
                "autoHeight": true,
                "mouseDrag": true,
                "touchDrag": true,
                "smartSpeed": 800
            }
        }'>
    <?php $index = 1; ?>
    <?php foreach($lookCollection as $look): ?>
        <?php $look->load($look->getId()) ?>
        <div class="item">
            <div class='aspot-container'>
                <div class='aspot-img'>
                    <picture>
                        <source srcset='/pub/media/wysiwyg/venia/look/aspot/VENIA_Outfit-<?= $look->getLookBookMainImage() ?>_lg@2x.jpg' media='(min-width: 1261px)'>
                        <source srcset='/pub/media/wysiwyg/venia/look/aspot/VENIA_Outfit-<?= $look->getLookBookMainImage() ?>_lg.jpg, /pub/media/wysiwyg/venia/look/aspot/VENIA_Outfit-<?= $look->getLookBookMainImage() ?>_lg@2x.jpg 2x' media='(min-width: 771px)'>
                        <source srcset='/pub/media/wysiwyg/venia/look/aspot/VENIA_Outfit-<?= $look->getLookBookMainImage() ?>_tab.jpg, /pub/media/wysiwyg/venia/look/aspot/VENIA_Outfit-<?= $look->getLookBookMainImage() ?>_tab@2x.jpg 2x' media='(min-width: 401px)'>
                        <img srcset='/pub/media/wysiwyg/venia/look/aspot/VENIA_Outfit-<?= $look->getLookBookMainImage() ?>_mobi@2x.jpg 2x'>
                    </picture>
                    <div class='details'>
                        <div class='headline'><?= $look->getName() ?></div>
                        <div class='subtitle'><?= $look->getDescription() ?></div>
                        <div class='button shop-this-look' data-load-url="<?= $block->getLookUrl($look) ?>"><?= __('Shop This Look') ?></div>
                    </div>
                </div>
                <div class='aspot-promo'>
                    <?php foreach($look->getProductCollection() as $product): ?>
                    <?php $product = $product->load($product->getId()) ?>
                    <div class='promo'>
                        <div class='details'>
                            <div class='headline'><?= $product->getLookBookHeadline() ?></div>
                            <div class='subtitle'><?= $product->getLookBookSubtitle() ?></div>
                        </div>
                        <div class='image'>
                            <picture>
                                <source srcset='/pub/media/wysiwyg/venia/look/promo/<?= $product->getLookBookImage() ?>_sm.jpg, /pub/media/wysiwyg/venia/look/promo/<?= $product->getLookBookImage() ?>_sm@2x.jpg 2x' media='(min-width: 771px)'>
                                <img srcset='/pub/media/wysiwyg/venia/look/promo/<?= $product->getLookBookImage() ?>.jpg, /pub/media/wysiwyg/venia/look/promo/<?= $product->getLookBookImage() ?>@2x.jpg 2x'>
                            </picture>
                        </div>
                    </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
        <?php $index++; ?>
    <?php endforeach ?>
    </div>
    <div class="lookbook-view" data-mage-init='{
            "MagentoEse_LookBook::lookbook": {
                    "modalClass":"lookbook",
                    "trigger":".shop-this-look",
                    "buttons":[]
            }
        }'>
    </div>
</div>
