<?php
/** @var \MagentoEse\LookBook\Block\LookBook $block */
?>
<?php $lookCollection = $block->getLookCollection() ?>
<div class="lookbook">
    <div class="prev"></div>
    <div class="next"></div>
    <div class="lookbook-carousel" data-mage-init='{
            "MagentoEse_LookBook::carousel": {
                "items": 1,
                "loop": true,
                "autoplay": false,
                "autoplayHoverPause": true,
                "responsive": true,
                "autoHeight": true,
                "mouseDrag": true,
                "touchDrag": true,
                "lazyLoad": true,
                "smartSpeed": 800
            }
        }'>
    <?php foreach($lookCollection as $look): ?>
        <?php $sortedPromos = $block->getSortedPromosByLook($look) ?>
        <div class="item">
            <div class='aspot-container'>
                <div class='aspot-img'>
                    <picture>
                        <source srcset='<?= $block->getCarouselMediaUrl($look->getLookBookMainImage() . '_lg@2x.jpg') ?>' media='(min-width: 1261px)'>
                        <source srcset='<?= $block->getCarouselMediaUrl($look->getLookBookMainImage() . '_lg.jpg') ?>, <?= $block->getCarouselMediaUrl($look->getLookBookMainImage() . '_lg@2x.jpg') ?> 2x' media='(min-width: 771px)'>
                        <source srcset='<?= $block->getCarouselMediaUrl($look->getLookBookMainImage() . '_tab.jpg') ?>, <?= $block->getCarouselMediaUrl($look->getLookBookMainImage() . '_tab@2x.jpg') ?> 2x' media='(min-width: 401px)'>
                        <img srcset='<?= $block->getCarouselMediaUrl($look->getLookBookMainImage() . '_mobi@2x.jpg') ?> 2x'>
                    </picture>
                    <div class='details'>
                        <div class='headline'><?= $look->getName() ?></div>
                        <div class='subtitle'><?= $look->getDescription() ?></div>
                        <div class='button shop-this-look' data-load-url="<?= $block->getLookViewUrl($look) ?>"><?= __('Shop This Look') ?></div>
                    </div>
                </div>
                <div class='aspot-promo'>
                    <?php foreach($sortedPromos as $promo): ?>
                    <div class='promo'>
                        <div class='details'>
                            <div class='headline'><?= $promo->getLookBookHeadline() ?></div>
                            <div class='subtitle'><?= $promo->getLookBookSubtitle() ?></div>
                        </div>
                        <div class='image'>
                            <picture>
                                <source srcset='<?= $block->getPromoMediaUrl($promo->getLookBookImage() . '_sm.jpg') ?>, <?= $block->getPromoMediaUrl($promo->getLookBookImage() . '_sm@2x.jpg') ?> 2x' media='(min-width: 771px)'>
                                <img srcset='<?= $block->getPromoMediaUrl($promo->getLookBookImage() . '.jpg') ?>, <?= $block->getPromoMediaUrl($promo->getLookBookImage() . '@2x.jpg') ?> 2x'>
                            </picture>
                        </div>
                    </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    <?php endforeach ?>
    </div>
    <div class="lookbook-view" data-mage-init='{
            "MagentoEse_LookBook::lookbook": {
                    "modalClass":"lookbook",
                    "trigger":".shop-this-look",
                    "title": "<?= __('Shop This Look') ?>",
                    "type": "modal",
                    "reaponsive": true,
                    "buttons":[]
            }
        }'>
    </div>
</div>
