<?php
    /** @var \MagentoEse\LookBook\Block\LookBook\View $block */
    $productCollection = $block->getLoadedProductCollection();
    $helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if ($productCollection->count()): ?>
    <div class="products wrapper">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($productCollection as $product): ?>
                <li class="item product product-item"
                        data-load-url="<?= $block->getDetailUrl($product) ?>"
                        data-defer="<?= $iterator++ == 1 ? 'false' : 'true' ?>"
                    >
                    <div class="product-item-info" data-container="product-grid">
                        <?php $productImage = $block->getImage($product, 'category_page_grid'); ?>
                        <?= $productImage->toHtml() // Product Image ?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="product wrapper">
        <div class="loader">
            <img src="<?= $block->getViewFileUrl('images/loader-1.gif') ?>" />
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            ".product-item": {
                "MagentoEse_LookBook::lookbookLoadDetail": {
                    "listenEvent": "click",
                    "elementSelector": ".product.wrapper"
                }
            }
        }
    </script>
<?php endif; ?>

