<?php
    /** @var \MagentoEse\LookBook\Block\LookBook\View $block */
    $productCollection = $block->getLoadedProductCollection();
    $helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if ($productCollection->count()): ?>
    <div class="products wrapper">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($productCollection as $product): ?>
                <?= ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid" data-load-url="<?= $block->getDetailUrl($product) ?>">
                    <?php $productImage = $block->getImage($product, 'category_page_grid'); ?>
                    <?= $productImage->toHtml() // Product Image ?>
                </div>
                <?= ($iterator == count($productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="product wrapper" data-mage-init='{
            "MagentoEse_LookBook::lookbookLoadDetail": {
                "loadUrl": "<?= $block->getDefaultDetailUrl() ?>",
                "defer": false
            }
        }'>
        <div class="loader">
            <img src="<?= $block->getViewFileUrl('images/loader-1.gif') ?>" />
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            ".product-item-info": {
                "MagentoEse_LookBook::lookbookLoadDetail": {
                    "listenEvent": "click",
                    "elementSelector": ".product:MagentoEse_LookBook-lookbookLoadDetail"
                }
            }
        }
    </script>
<?php endif; ?>